#spring.application.name=product-service
#server.port=8989
#spring.data.mongodb.host= localhost
#spring.data.mongodb.port= 27017
#spring.data.mongodb.database= ecommerce
#management.health.circuitbreakers.enabled=true
#management.health.ratelimiters.enabled=true
#resilience4j.circuitbreaker.instances.CircuitBreakerService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.CircuitBreakerService.minimum-number-of-calls=5
#resilience4j.circuitbreaker.instances.CircuitBreakerService.automatic-transition-from-open-to-half-open-enabled=true
#resilience4j.circuitbreaker.instances.CircuitBreakerService.wait-duration-in-open-state=5s
#resilience4j.circuitbreaker.instances.CircuitBreakerService.permitted-number-of-calls-in-half-open-state=3
#resilience4j.circuitbreaker.instances.CircuitBreakerService.sliding-window-size=10
#resilience4j.circuitbreaker.instances.CircuitBreakerService.sliding-window-type=count_based

server:
  port: 8989

spring:
  application:
    name: productService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


